### ISSUE TITLE
[Feature] Add Sharepoint datasoure

### ISSUE THREAD

**Issue by mawandm** [ametnes/nesis#19]
**Describe the solution you'd like**
This feature adds Sharepoint as a datasource.

**Additional context**
This particularly useful for Microsoft shops

**Comment by mawandm** [comment]
@akizito See https://dev.to/nbelyh/using-a-certificate-auth-to-call-sharepoint-rest-api-csom-1gh8 on authenticating with Sharepoint using certificates. I'm suspecting this might be more reliable than refresh token exchanges that seem to be the other alternative since basic auth isn't not possible

**Comment by akizito** [comment]
ok taking a look at this
